### PR TITLE
Listen to request error event

### LINKED ISSUE #8: Unhandled 'error' event
There is no listener for error events so the process will crash in case of socket error e.g.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1092:19)
    at TLSSocket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### PR DESCRIPTION
**Pull request by jtblin**
Fix #8

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -191,12 +191,16 @@ CloudFront.prototype.request = function(method, path, headers, cb) {
 
       cb(err, info);
     });
-    parser.on("error", function(err) {
-      cb(err, info);
+    parser.on('error', function(err) {
+      cb(err);
```
Comment (tellnes) [inline lib/index.js]: Is there a reason you are removing the `info` object here?

File: lib/index.js [hunk 2]
```diff
@@ -191,12 +191,16 @@ CloudFront.prototype.request = function(method, path, headers, cb) {
...
     });
 
   });
 
+  req.on('error', function(err) {
```
Comment (tellnes) [inline lib/index.js]: If I remember correctly it is possible to receive an `error` event after the `response` event. We should probably add some code to handle that. Otherwise, this is better than not having this.

File: lib/index.js (hunk 1 above)
Comment (jtblin) [inline lib/index.js]: Oops, sorry no reason. I actually follow the same signature for the error on req. Putting it back.

File: lib/index.js (hunk 2 above)
Comment (jtblin) [inline lib/index.js]: Receiving an error on the response? I don't think I've seen that.

Comment (jtblin) [inline lib/index.js]: I mean this code will be executed before the response event is received anyway so it would work even if the error event is received after the response event is received.

**Comment by jtblin** [comment]
OK to merge?

File: lib/index.js (hunk 2 above)
Comment (tellnes) [inline lib/index.js]: Yeah, just that the callback might be called twice. But you may be right that you will never see both an `response` and `error` event.

**Review by tellnes — APPROVED** [review]

**Comment by tellnes** [comment]
Fell free to merge

**Comment by jtblin** [comment]
Done, I've increased the patch version and pushed to master as well but can't publish to npm so you'll have to do that (or give me access to that too).

**Comment by tellnes** [comment]
Published to npm. I'll add you (or someone else active when that happens) as owner to npm if I'm unavailable to continue supporting this module.
